//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recursos_Humanos_P3
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empleado()
        {
            this.departamento1 = new HashSet<departamento>();
            this.salida_empleado = new HashSet<salida_empleado>();
            this.licencia = new HashSet<licencia>();
            this.permiso = new HashSet<permiso>();
            this.vacacion = new HashSet<vacacion>();
        }
    
        public int id { get; set; }

        [Required(ErrorMessage ="El código del empleado es requerido")]
        public string Codigo_Empleado { get; set; }

        [Required(ErrorMessage = "El nombre del empleado es requerido")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "El apellido del empleado es requerido")]
        public string Apellido { get; set; }
        public Nullable<int> id_departamento { get; set; }
        public Nullable<int> id_cargo { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public Nullable<decimal> salario { get; set; }
        public string estatus { get; set; }
        public string telefono { get; set; }
    
        public virtual cargo cargo { get; set; }
        public virtual departamento departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<departamento> departamento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<salida_empleado> salida_empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<licencia> licencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<permiso> permiso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vacacion> vacacion { get; set; }
    }
}
